#ifndef __PXR_IMAGING_HDSI_H__
#define __PXR_IMAGING_HDSI_H__

// HdSi
#include <HdSi/api.h>
#include <HdSi/coordSysPrimSceneIndex.h>
#include <HdSi/extComputationPrimvarPruningSceneIndex.h>
#include <HdSi/implicitSurfaceSceneIndex.h>
#include <HdSi/legacyDisplayStyleOverrideSceneIndex.h>
#include <HdSi/lightLinkingSceneIndex.h>
#include <HdSi/materialBindingResolvingSceneIndex.h>
#include <HdSi/materialPrimvarTransferSceneIndex.h>
#include <HdSi/nurbsApproximatingSceneIndex.h>
#include <HdSi/pinnedCurveExpandingSceneIndex.h>
#include <HdSi/primManagingSceneIndexObserver.h>
#include <HdSi/primTypeNoticeBatchingSceneIndex.h>
#include <HdSi/primTypePruningSceneIndex.h>
#include <HdSi/renderSettingsFilteringSceneIndex.h>
#include <HdSi/sceneGlobalsSceneIndex.h>
#include <HdSi/tetMeshConversionSceneIndex.h>
#include <HdSi/utils.h>
#include <HdSi/velocityMotionResolvingSceneIndex.h>
#include <HdSi/version.h>
#include <HdSi/materialOverrideResolvingSceneIndex.h>
#include <HdSi/computeSceneIndexDiff.h>
#include <HdSi/extComputationDependencySceneIndex.h>
#include <HdSi/primTypeAndPathPruningSceneIndex.h>
#include <HdSi/debuggingSceneIndex.h>
#include <HdSi/prefixPathPruningSceneIndex.h>
#include <HdSi/switchingSceneIndex.h>
#include <HdSi/domeLightCameraVisibilitySceneIndex.h>
#include <HdSi/unboundMaterialPruningSceneIndex.h>
#include <HdSi/sceneMaterialPruningSceneIndex.h>
#include <HdSi/debuggingSceneIndexPlugin.h>
#include <HdSi/renderPassPruneSceneIndex.h>
#include <HdSi/nodeIdentifierResolvingSceneIndex.h>
#endif  // __PXR_IMAGING_HDSI_H__
